### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Interfiber** [Interfiber/pack#1]
- [x] Add list command 

- [x] Add update command

 - [x] Add GUI installer
